// <auto-generated />
namespace Query.Sample.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCuitToEmpleado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCuitToEmpleado));
        
        string IMigrationMetadata.Id
        {
            get { return "201309260023478_AddCuitToEmpleado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
