// <auto-generated />
namespace Query.Sample.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddAverageHourlyWateToEmpleado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAverageHourlyWateToEmpleado));
        
        string IMigrationMetadata.Id
        {
            get { return "201309262253081_AddAverageHourlyWateToEmpleado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
