// <auto-generated />
namespace Query.Sample.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Addattachment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addattachment));
        
        string IMigrationMetadata.Id
        {
            get { return "201308272157385_Add attachment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
